# Generated by Django 5.2 on 2025-05-27 04:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SanitizationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                (
                    "reporter_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not cleaned", "Not Cleaned"),
                            ("Not properly cleaned", "Not properly cleaned"),
                            ("cleaned up", "cleaned up"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Top", "Top"),
                            ("Average", "Average"),
                            ("Less", "Less"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("report", models.CharField(max_length=1000, null=True)),
                (
                    "reporter_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, null=True)),
                ("dept", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        default="user_icon.webp",
                        null=True,
                        upload_to="images/",
                    ),
                ),
                ("dob", models.DateField(default=django.utils.timezone.now)),
                ("supervisor", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(blank=True, max_length=200, null=True)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "notice",
                    models.CharField(
                        choices=[
                            ("task completed", "Task completed"),
                            ("new report", "new report"),
                            ("new task", "new task"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reporter",
                        to="core.sanitizationreport",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver",
                        to="core.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_type", models.CharField(max_length=20, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In progress", "In progress"),
                            ("Finished", "Finished"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Top", "Top"),
                            ("Average", "Average"),
                            ("Less", "Less"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("due_date", models.DateField(null=True)),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("up_date", models.DateTimeField(auto_now=True)),
                ("assigned_to", models.ManyToManyField(blank=True, to="core.staff")),
            ],
        ),
    ]
