# Generated by Django 5.2 on 2025-05-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sanitizationreport",
            name="status",
        ),
        migrations.AlterField(
            model_name="task",
            name="created_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
